package com.example.shirocheng.mqttclient.db.dao;

import com.example.shirocheng.mqttclient.bean.Connection;
import com.example.shirocheng.mqttclient.bean.Subscription;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subscriptionDaoConfig;
    private final DaoConfig connectionDaoConfig;

    private final SubscriptionDao subscriptionDao;
    private final ConnectionDao connectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subscriptionDaoConfig = daoConfigMap.get(SubscriptionDao.class).clone();
        subscriptionDaoConfig.initIdentityScope(type);

        connectionDaoConfig = daoConfigMap.get(ConnectionDao.class).clone();
        connectionDaoConfig.initIdentityScope(type);

        subscriptionDao = new SubscriptionDao(subscriptionDaoConfig, this);
        connectionDao = new ConnectionDao(connectionDaoConfig, this);

        registerDao(Subscription.class, subscriptionDao);
        registerDao(Connection.class, connectionDao);
    }

    public void clear() {
        subscriptionDaoConfig.clearIdentityScope();
        connectionDaoConfig.clearIdentityScope();
    }

    public SubscriptionDao getSubscriptionDao() {
        return subscriptionDao;
    }

    public ConnectionDao getConnectionDao() {
        return connectionDao;
    }

}
